### ISSUE TITLE
Validacion de formularios

### ISSUE THREAD

**Issue by ANicoGamarra** [PuebladaFactory/ApLog#21]
- [x] Tipo de dato: numero, letra, ambos etc..
- [x] Cantidad de dígitos
- [x] Formato: mail, patente, etc
- [x] Alertas de errores

**Comment by nanreh1976** [comment]
recien hecho en rama validators, esta alta de clientes, choferes, proveedores

**Comment by nanreh1976** [comment]
cerrado
